// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL5VJHalHYPSjPlzbel8Oyasonv0ByQNM',
    appId: '1:704830984916:web:87a6ceeca7a69d3d456141',
    messagingSenderId: '704830984916',
    projectId: 'flutter-app-a01e3',
    authDomain: 'flutter-app-a01e3.firebaseapp.com',
    storageBucket: 'flutter-app-a01e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEbfO3FyncavDq5GTM0QGmuqP2L1fPuAM',
    appId: '1:704830984916:android:3da013bcdd37d622456141',
    messagingSenderId: '704830984916',
    projectId: 'flutter-app-a01e3',
    storageBucket: 'flutter-app-a01e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlDwforY3KGJxH1N_tybOdnUU7FbSIHrQ',
    appId: '1:704830984916:ios:a669252343aa16ad456141',
    messagingSenderId: '704830984916',
    projectId: 'flutter-app-a01e3',
    storageBucket: 'flutter-app-a01e3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlDwforY3KGJxH1N_tybOdnUU7FbSIHrQ',
    appId: '1:704830984916:ios:2a566c998ee7bb6c456141',
    messagingSenderId: '704830984916',
    projectId: 'flutter-app-a01e3',
    storageBucket: 'flutter-app-a01e3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
